/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SproutLazyImport = createFileRoute('/sprout')()
const AppcuesLazyImport = createFileRoute('/appcues')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SproutLazyRoute = SproutLazyImport.update({
  id: '/sprout',
  path: '/sprout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sprout.lazy').then((d) => d.Route))

const AppcuesLazyRoute = AppcuesLazyImport.update({
  id: '/appcues',
  path: '/appcues',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/appcues.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/appcues': {
      id: '/appcues'
      path: '/appcues'
      fullPath: '/appcues'
      preLoaderRoute: typeof AppcuesLazyImport
      parentRoute: typeof rootRoute
    }
    '/sprout': {
      id: '/sprout'
      path: '/sprout'
      fullPath: '/sprout'
      preLoaderRoute: typeof SproutLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/appcues': typeof AppcuesLazyRoute
  '/sprout': typeof SproutLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/appcues': typeof AppcuesLazyRoute
  '/sprout': typeof SproutLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/appcues': typeof AppcuesLazyRoute
  '/sprout': typeof SproutLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/appcues' | '/sprout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/appcues' | '/sprout'
  id: '__root__' | '/' | '/about' | '/appcues' | '/sprout'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  AppcuesLazyRoute: typeof AppcuesLazyRoute
  SproutLazyRoute: typeof SproutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  AppcuesLazyRoute: AppcuesLazyRoute,
  SproutLazyRoute: SproutLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/appcues",
        "/sprout"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/appcues": {
      "filePath": "appcues.lazy.tsx"
    },
    "/sprout": {
      "filePath": "sprout.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
